### ISSUE TITLE
Write mock scenario involving 2 daemons, 1 API and a MySQL instance

### ISSUE THREAD

**Issue by iprunache** [cami-project/cami-project#10]
## Why

We need to test and showcase that the parts of the infrastructure work together. The first step is to tests message passing, REST API and database access. The script can then be extended and tweaked to implement the entire Episode H4.1 with mocked services.
## What
- [ ] write a script implementing a scenario similar to Episode H4.1
  - [ ] script writes to queue to notify daemon 1 of event
  - [ ] daemon 1 requests info from daemon 2 
  - [ ] daemon 2 reads info from DB through the API
  - [ ] daemon 2 writes the requested info on daemon 1's queue
  - [ ] daemon 1 writes processed info on queue to which the script subscribed.

**Comment by iprunache** [comment]
Part of #5 .

**Comment by rtud** [comment]
@iprunache: this issue has since been deprecated. closing, thank you!
