### ISSUE TITLE
Create Celery task that stores Heart Rate data

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#100]
## Why
As a Caregiver using the CAMI system to take care of an Elder, having updated information on his heart rate and step count, helps me understand if his current condition is in order, or if there are any problems regarding his overall health or lack of exercise. This in turn will help CAMI and myself to take action in time.

Taking into account that as of #99 we have the means to fetch the Heart Rate information via the Google Fit API, we must also implement a handler function that will store it inside the CAMI Cloud setup in #97.

## What
* [x] a task that handles storing the Google Fit data is implemented

**Comment by cretualexandru** [comment]
After all, there was no need to separate grabbing data and saving the data in two different tasks. Only one task that handles both actions was created, in PR #101. Closed!
