### ISSUE TITLE
Setup Docker container running cami daemon

### ISSUE THREAD

**Issue by iprunache** [cami-project/cami-project#12]
## Why

In order to integrate the cami daemon with other service we'll need to run it in a container.
## What
- [ ] parameterise the daemon through a settings file
  - [ ] configure the IP address of the RabbitMQ broker
  - [ ] configure credentials for RabbitMQ
  - [ ] configure vhost
- [ ] update Ansible recipe to provision daemon config file by using a template
- [ ] write Docker config that creates a container and provisions it with the daemon Ansible recipe.

**Comment by rtud** [comment]
@iprunache: The CAMI docker setup has since been implemented and is already deployed into production. Closing, thank you!

/cc @aismail
