### ISSUE TITLE
CAMI -> OpenTele API Analysis

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#125]
## Why
As a developer I want to be able to synchronize any user measurement updates taken through the CAMI platform (e.g. weight from Withings scale, pulse data from LG watch) with the OpenTele platform, developed by Aliviate (Denmark).
This is required as part of the frontend integration with 3rd party services developed by the CAMI project partners.

## What
* [x] an API test environment using Postman, which showcases the API calls for getting/sending measurements to the OpenTele demo account
* [x] documentation explaining how to setup and use the test environment

**Comment by asorici** [comment]
**Setup the OpenTele test environment**
  - install [Postman](https://www.google.ro/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&sqi=2&ved=0ahUKEwjUia2Sn6jRAhVCOBQKHagqAAQQFggZMAA&url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fpostman%2Ffhbjgbiflinjbdggehcddcbncdddomop%3Fhl%3Den&usg=AFQjCNE_Yq59TT1ZExzJ68FTldg4ho_lGw&sig2=KzbTW2-HaPw7cAPw54PQUA&bvm=bv.142059868,d.ZWM) Chrome App from Chrome Webstore

  - configure the OpenTele environment:
      - in the Postman UI, locate the settings wheel in the upper right corner
      - select manage environments and select import
      - import the `OpenTeleRest.postman_environment.json` file shared on Slack
  
  - configure the OpenTele call collection:
      - click the import button in the upper left corner of the Postman UI
      - select import from link and insert this URI: `https://www.getpostman.com/collections/443280e88ba69fb52b83`

**Run the API calls**
  - make sure the OpenTeleREST environment is selected in the top right dropdown
  - in the left sidebar, open the OpenTeleREST call collection. You can:
      - get the list of "questionnaires" (OpenTele term for set of requested measurements)
      - get/post weight measurements
      - get/post BP and pulse measurements

  - all API calls use HTTP Basic Authentication (user=nancyann + password=abcd1234), so make sure to select BasicAuth in the Authorziation tab if it is not selected already
  - the Body tab shows the JSON payload that is sent as part of the call - pretty straightforward

**Notes**
  - the OpenTele server does NOT perform any duplicate check (i.e. two measurements with same timestamp), so it is our responsability to ensure uniqueness

**Comment by aismail** [comment]
@asorici as per our discussion today, you will also provide us with a Python script to do this. Thanks!

**Comment by asorici** [comment]
The script from commit bff0032 performs a simple demo of sending and retrieving weight and BP measurements to the OpenTele server.

OpenTele uses BasicAuthentication as security measure. 

The response message to POST requestes is not at all informative, so just the status code of the send measurement operation is checked.

**Comment by aismail** [comment]
This is already done. Closing!
