### ISSUE TITLE
Investigate CAMI Cloud's integration with Linkwatch's API 

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#135]
## Why
The CAMI project allows for all the stakeholders involved to contribute to the development and extension of its features. This entails that the information that is collected under the CAMI cloud must also be shared with the other stakeholders' systems. 

An initial inspection of the Linkwatch integration functionality showed that although the data is being sent to their API, it doesn't show up in their front-end at: [MyLinkWatch](http://www.mylinkwatch.se/my-measurements/)

## What
* [ ] following the progress made in #121 & #124, the integration is tested end to end and the data is correctly sent and displayed in the Linkwatch system for the following metrics:
   * [ ] Heart Rate
   * [x] Weight
   * [ ] Step Count

## Notes

**Comment by aismail** [comment]
Closing as this issue's "What" will lead to a rabbithole due to being too vague.
