### ISSUE TITLE
Integrate calendar component into React Native app - draft

### ISSUE THREAD

**Issue by aismail** [cami-project/cami-project#145]
## Why
Following #144, we will have a draft design vectorised for the calendar component, that is adapted to the existing calendar plugins on the market for React Native.

## What
* [ ] a calendar plugin for React Native is chosen for the mobile app
* [ ] said calendar plugin is integrated (with minimal customizations) in the mobile app
* [ ] list of follow-up Github issues for customizations is created

**Comment by rtud** [comment]
Following the work done in #144, we're no longer making use of a calendar component, and instead displaying the events in a simple chronological manner.

I have created issue #157 as a follow-up and closing this one, thank you! /cc @aismail
