### ISSUE TITLE
Move PaperTrail alerts to #cami-bots channel

### ISSUE THREAD

**Issue by aismail** [cami-project/cami-project#146]
## Why
We need to be on top of errors related to the CAMI project.

## What
* [x] saved search with alerts for `CAMI` project is redefined to only point to the `CAMI` group in PaperTrail
 * otherwise it's a permissioning error for users who need to access it and don't have full access (eg Alex)
* [x] PaperTrail integration is moved to the `#cami-bots` channel

**Comment by rtud** [comment]
@aismail: I have tweaked the configuration for Papertrail to Slack notifications. Closing, thank you!
