### ISSUE TITLE
Rebuild pulse and steps measurement pipeline using CAMI Store API

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#159]
## Why
Following the outline in #152, the processing of step and pulse measurements from the LG Urbane smartwatch scale must make use of the new CAMI Store API, such that a uniform view of an end-user measurements can be obtained.

## What
 * [x] measurement is stored using an POST request to the CAMI Store Measurements endpoint
 * [ ] the link between the measurement device (LG watch) and the retrieval from Google Fit is made explicit in the celery tasks
 * [ ] access to Google Fit credentials is obtained via a query to a corresponding DeviceUsage endpoint
 * [x] update broadcast to third party integration to reflect new pulse and step measurements data form

**Comment by aismail** [comment]
@cretualexandru please take a look at this. Thanks :)

**Comment by asorici** [comment]
This tasks in this issue are dependent on the infrastructure refactoring proposed in #221. The latter entails that CAMI Store Management API is used for all interactions with the stored measurement data.

Since follow up issues are expected from #221, the outstanding tasks from this issue should be revisited at that point.
Closing, thank you.
