### ISSUE TITLE
QA for Google Calendar code

### ISSUE THREAD

**Issue by aismail** [cami-project/cami-project#163]
## Why
Next week demo

## What
* [ ] access to Google Calendar used for testing is gained by @cretualexandru 
* [ ] testing is performed in order to check if adding a new event is processed by the CAMI cloud backend
* [ ] release checklist is updated to include Google Calendar checks
* [ ] list of follow-up issues is created

**Comment by cretualexandru** [comment]
The integration is incomplete, opened #189 for fully implementing it.
