### ISSUE TITLE
QA Linkwatch + OpenTele

### ISSUE THREAD

**Issue by aismail** [cami-project/cami-project#165]
## Why
Next week's demo.

## What
* [ ] data replication towards Linkwatch is tested
* [ ] data replication towards OpenTele is tested
* [x] release checklist is updated with the necessary items
* [ ] follow-up issues are created for the bugs found

**Comment by rtud** [comment]
We're tending to WIthings to 3rd party API testing in #175 & #176.

Follow-up issues for testing Google Fit to 3rd party API testing will be created, once we have a working Google Fit data fetch in #173.
