### ISSUE TITLE
Implement end-to-end push notifications demo

### ISSUE THREAD

**Issue by iprunache** [cami-project/cami-project#17]
## Why

We will use push notifications as a first step of delivering notifications from the CAMI box to an iOS app. We need a working skeleton for sending push notifications upon which to build the app.
## What

Set up environment
- [x] install node with installer
- [x] fix permissions manually with home dir

Apple developer
- [ ] create certificate for push notifications

Backend
- [ ] install certificate
- [ ] write script that sends notifications

XCode project
- [ ] configure app for push notifications

React Native
- [ ] use react native cli to init a project
- [ ] get an app running in simulator
- [ ] write skeleton app that can ingest push notifications
## Notes

This is an umbrella issue for documenting the steps we expect to accomplish in getting a working demo. Sub-issues will be created for more detail for each component involved.

**Comment by rtud** [comment]
@iprunache: as specified for #19 as well, this has already been successfully tended to. Closing, thank you!
