### ISSUE TITLE
Ensure that the iOS app is installed as iPhone app on iPads

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#170]
## Why
At the end of the following week, we'll need to showcase the app's functionality as part of the CAMI Consortium meeting.

The demo will make use of the 2 devices available to UPB: an iPhone and an iPad. The former will be logged in the Caregiver version while the former in the Elder's, showcasing an end-to-end functionality of the current system.

As of this time, the iOS application's design hasn't been extended to support iPad layouts, and it has been restricted to an iPhone-only version in cc2b2e4399aca51db5a3f91a897b3ae50a955b5c for safeguarding against visual glitches.

## What
* [x] the iOS app is tested on a real iPad insuring that:
   * [x] the iPad's UDID is added to the whitelist and the app is re-exported
   * [x] the application is installed successfully on the iPad
   * [x] the application displays accordingly as a scaled iPhone app

**Comment by aismail** [comment]
App needs some love to display as awesome on iPad as on iPhone. Creating follow-up issue for that.
