### ISSUE TITLE
Google Fit data fetch does not save data to the store

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#173]
## Why
Following the task list in #164, the errors in process_heart_rate_measurement() and process_steps_measurement() from medical_compliance service are corrected. The problem stems from an incorrect attempt to retrieve the google_fit_userid from previous measurements.

## What
 * [x] google_fit userid is left hardcoded (as before PR #151) to ensure proper code flow

**Comment by cretualexandru** [comment]
Fixed in #174 .
