### ISSUE TITLE
Integrate Google Calendar events in mobile app

### ISSUE THREAD

**Issue by aismail** [cami-project/cami-project#187]
## Why
In #157 we've added the Activities screen to the iOS application, that used a HC data json to display events.

We now need to adapt the iOS application to display actual events fetched from the API.

## What
* [x] smaller follow-up issues are created to complete the iOS app's integration with the Google Calendar events via the CAMI API

**Comment by rtud** [comment]
The Google Calendar integration w/ the iOS app via the API is now finalized, and I have exported [version 1.2.4.1](https://vitaminsoftware.slack.com/files/rtud/F5E3TV136/2017-05-16-cami-vs-1.2.4.1.ipa). Closing this, thank you!
