### ISSUE TITLE
Investigate measurements not being sent in chronological order

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#188]
## Why
As a user of the CAMI system, I need to be sure that of the latest information that I receive so that I can take action immediately if needed.

Right now, when adding measurements retroactively they're being sent to the front-end app unsorted, with the latest addition up front, just like this:

![CAMI Status Screen unordered measurements](http://mq.d.pr/3voN.jpg)

## What
* [x] the cause for unordered data being sent is investigated and follow-up issues are created, so that the following scenario works as expected:
   1. visit the Withings dashboard using the credentials from LastPass
   2. add a new weight measurement and date it for the day before
   3. the iOS app's Status screen displays the measurements in chronological order

**Comment by cretualexandru** [comment]
The API returns the sorted set of values. Also, we can not reproduce the issue anymore.
