### ISSUE TITLE
Implement React Native iOS app that is able to consume push notifications

### ISSUE THREAD

**Issue by iprunache** [cami-project/cami-project#19]
## Why

The Patient and Caregiver apps need to receive notifications from the cami box and push notifications are the first step for delivering them
## What
- [ ] initialize project
- [ ] configure project for push notifications
- [ ] add code for handling push notifications

**Comment by rtud** [comment]
@iprunache: a push notifications system has since been implemented by @paraschivionut. Closing this issue, thanks!
