### ISSUE TITLE
Investigate means to retrieve home monitoring events from SNG Gateway

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#206]
## Why
Home monitoring events need to be included as part of a service of the CAMI Gateway and forwarded to the CAMI cloud.

## What
   - [x] document API endpoints for accessing health and home monitoring data
   - [ ] investigate options for transfering data collected from SNG Gateway to CAMI Measurement endpoints

## Notes
The second task should generate follow-up issues that constitute implementation steps from the performed investigation outcome.

**Comment by aismail** [comment]
@asorici what's the blocker here?

**Comment by asorici** [comment]
@nikooo777 in order to push the integration of the EXYS Gateway with the CAMI cloud as soon as possible into production, we need to have a resolution on this issue.
I'm closing this issue and creating follow-up issues. Thank you!

**Comment by nikooo777** [comment]
fair enough, i just got around to testing the forwarding service so we should be close
