### ISSUE TITLE
Upgrage @aismail's apple developer account from individual to company

### ISSUE THREAD

**Issue by iprunache** [cami-project/cami-project#21]
## Why

We want multiple developers to work on the same app so we need a company developer account that supports team of developers. @aismail already has a payed individual account that we should upgrade to company so we don't pay for 2 accounts.
## What
- [ ] contact Apple Developer Program Support to find out what is needed
- [ ] provide company d-u-n-s number
- [ ] demonstrate executive role in the company for @aismail so he can register a company account

**Comment by rtud** [comment]
@iprunache: for the time being we circumvented the need for @aismail's Apple Dev Acc, by working locally, having @paraschivionut package new builds and installing it manually using iTunes. We'll re-open this issue if need be. Closing, thank you!
