### ISSUE TITLE
Document Linkwatch Measurement Format

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#216]
## Why
As a developer of CAMI, I need to have access to data collected from the Linkwatch platform running on iOS devices. The collector application already uses a standard format for representing measurements. This format needs to be documented such that a service running in the CAMI Cloud can perform conversion and insert it in the CAMI Store.

## What
  - [x] documentation describing format of measurements in Linkwatch and example of GET/POST requests is given

**Comment by asorici** [comment]
We need to look into schema provided by the openmheatlh standard: 
http://www.openmhealth.org/
https://github.com/openmhealth

**Comment by tobiasbrodencnet** [comment]
Here is a summary and a brief explanation about the format. First some links to Open mHealth and the location of the JSON Schemas. Then links to the API in Azure with a Postman collection and finally an example and a description of the JSON format. 
[OpenmHealth_Format_Description.docx](https://github.com/cami-project/cami-project/files/1013814/OpenmHealth_Format_Description.docx)

There is also a method in the API (Overview) to get the latest measurement for all types. Retrived the data for CNetDemo, which could be a good example on how the measurements looks like.
[Get_Overview.zip](https://github.com/cami-project/cami-project/files/1013817/Get_Overview.zip)

**Comment by asorici** [comment]
Analysing the openMHealth format we determined that it might require more effort to implement a correct model directly in the CAMI Cloud, as opposed to forwarding the collected measurements from the Linkwatch Cloud to the CAMI cloud. 

We will reconsider issue after first CAMI MVP is implemented and tested end to end.

Closing, thank you.
