### ISSUE TITLE
Document List of Devices that can be used with the Linkwatch iOS data collection service

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#217]
## Why
For the upcoming pilot tests we have to be clear on the list of health measurement devices that we want to showcase. The Linkwatch data collection service runs on iOS to complement the CAMI iPhone application.
Since there are limitations to the set of Bluetooth enabled devices supported by Apple, a list of what devices are usable (and available for testing) is required. 

## What
  - [x] a document with the devices and the types of measurements we can collect from each one is provided

**Comment by tobiasbrodencnet** [comment]
[DeviceList.docx](https://github.com/cami-project/cami-project/files/1018179/DeviceList.docx)
