### ISSUE TITLE
Investigate refactoring of the STORE container

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#222]
## Why
Following our initial talks on #221, we have identified the `store` container as the one that we need to start the refactoring with.

This container is currently in charge of hosting the database for CAMI Cloud, but also handles the Google Calendar API integration. Also, instead of intermediating the communication with the database for the rest of the system via its API, most of the times the rest of the containers circumvent it and connect directly to the MySQL db.

## What
* [x] splitting the current `store`'s functionality into separate containers is investigated and follow-up issues are created for refactoring it, taking into account the plan laid out in #221

**Comment by cretualexandru** [comment]
Created follow-up tickets, closing this one!
