### ISSUE TITLE
Document install procedure of Linkwatch data collection application for iOS

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#224]
## Why
Following the progress in #223, to perform end-to-end testing we need to be able to install the Linkwatch data collection service for iOS on the same iPhone/iPad on which the CAMI caretaker/caregiver app runs.

## What
  - document steps needed to install the Linkwatch data collection service application on an iOS device.

**Comment by tobiasbrodencnet** [comment]
Still waiting for response from Apple regarding the TestFlight distribution of the application. 

Brief description on how to use the LinkWatch data collector together with A&D's offical appplication for their device. 
- Download offical A&D Connect Smart app from App Store. 
- Download LinkWatch data collector from AppStore/TestFlight, more instructions when it's ready. 
- Start A&D application and allow permission for Health. 
	- Pair devices from Menu -> Device Setup -> Connect blood pressure device and/or weighing scale.
- Take measurements when A&D application is running. 
- To sync data to LinkWatch, start LinkWatch data collector and login with credentials (only needed once). 
- It will sync automatically if measurement have been taken.

**Comment by asorici** [comment]
Marking this as done, since it requires a step that is pending external approval.
I have copied these instructions in this [google doc](https://docs.google.com/document/d/1WhQq7mIEh7Oa1vCIkNe62uIVS_9GK-L9Sajs6OUw7_o/edit), accessible to all partners in the CAMI Repository on Google Drive.

Please open follow up issue for documentation update when response from Apple is available.

Closing, thank you!
