### ISSUE TITLE
Document install procedure for CAMI caretaker/caregiver application

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#225]
## Why
Following the progress in #223, to perform end-to-end testing we need to be able to install the CAMI caretaker/caregiver application on the same iPhone/iPad on which the Linkwatch data collection service for iOS runs on.

## What
- [x] document steps needed to install the CAMI caretaker/caregiver application on an iOS device.

**Comment by rtud** [comment]
Following the meeting from June 21st, it's also been decided that we'll need to:
- [ ] upload the current and past builds for the iOS app inside [CAMI's Gdrive project repository](https://drive.google.com/drive/folders/0B_fjaGbXUSPIWUY0bDIyVmlDRDg)
- future builds will also be made available from the respective folder

**Comment by rtud** [comment]
@asorici: I've populated the Google Drive folder w/ all the builds we've gathered so far, and placed a Markdown version of the guide inside the repo & a PDF version inside the builds folder: https://drive.google.com/a/maronqua.ro/file/d/0B5R_gDLmaW5UMU81RE41Q2M1R3M/

Closing, thank you!
