### ISSUE TITLE
API documentation for CAMI Store and EXYS SNG Gateway

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#234]
## Why
The task of deploying the current CAMI Gateway on the physical SNG Gateway requires use of APIs from both CAMI store (storing measurements, getting device data) and the SNG Gateway (accessing home monitoring events).
Current documentation for both APIs is only given as examples, i.e. no explicit description of calls and parameters to calls.
To ensure easy use of the APIs in the consortium, an expliciti description of API endpoints is required

## What
  - [x] use [editor.swagger.io](url) to create explicit API descriptions for both EXYS Gateway, as well as CAMI Store

**Comment by cribov** [comment]
The swagger definition for the EXYS gateway has been completed. Awaiting for more details tomorrow during the telco.

**Comment by asorici** [comment]
Documentation for SNG Gateway has been provided.
Follow-up for CAMI Store documentation exists in #249.

Closing, thank you!
