### ISSUE TITLE
Investigate creation of 'contractor' container

### ISSUE THREAD

**Issue by cretualexandru** [cami-project/cami-project#252]
## Why
In order to follow the plan from #246, we need to create the `contractor` container which will be the central piece in the measurements analysis and storing process. Before we get there, we need to do some investigation and come up with a strong, in-depth plan, in order for the development to go smoothly.

## What
- [ ] Investigate what the creation of the `contractor` container implies
- [ ] Create a follow-up ticket that will describe the resulted plan

## Notes

**Comment by rtud** [comment]
Following an initial investigation by @cretualexandru on splitting the `medical_compliance` container, he came up w/ the following bare plan: https://github.com/cami-project/cami-project/issues/246#issuecomment-308274927

**Comment by cretualexandru** [comment]
This is no longer usable, we will create a fresh `medical_compliance` refactoring plan after we finish the reminders implementation.
