### ISSUE TITLE
Implement CAMI measurement and event insertion endpoints

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#254]
## Why
The convened upon architecture of the CAMI cloud sees all events and measurements enter the system via the CAMI Event Stream Manager (implemented as a RabbitMQ message broker instance).
Following the work in #245, the endpoint API for inserting measurements and events into the CAMI cloud has been defined.
The endpoints definition now needs to be implemented.

## What
  - [x] define a new Docker container implementing a CAMI Insertion Service
  - [x] implement the service as Django application with a _view_ for each type of data: health measurements and events
  - [x] the views implement the logic to insert the received data on the corresponding internal CAMI cloud RabbitMQ queue.

**Comment by cretualexandru** [comment]
This was implemented in #266. Thank you @asorici, closing!
