### ISSUE TITLE
CAMI Cloud needs data model for User Home Environment

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#283]
## Why
Health measurements and environment monitoring events need to be accompanied by traceability metadata for control and debugging purposes.
The CAMI data model needs to be augmented to include an identifier of the gateway that collects and forwards health or home monitoring data to the CAMI Cloud.  

## What
  - [ ] CAMI data model is updated to contain a reference to a UserEnvironment
  - [ ] UserEnvironment may contain 0 or more Gateways
  - [ ] Corresponding Tastypie resources are created and CAMI Measurement Insertion API documentation is updated

**Comment by rtud** [comment]
Following the discussion I've had w/ @asorici, we're closing this and creating a follow-up issue for simplified version. Thank you!
