### ISSUE TITLE
Investigate options for automatic build of DSS service

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#287]
## Why
Given that the DSS system is built using .NET and adapted to work on Ubuntu linux, we need a replicable way of compiling and building the required DSS executable that will be hosted in its own separate Docker container in the CAMI Cloud.

## What
* [x] a replicable solution for compiling the service is investigated and documented on this issue as a comment and a follow-up issue is created to implement it

**Comment by sabljakovich** [comment]
The [docker image ](https://hub.docker.com/_/mono/) used for this project includes everything required for compiling and running it.
