### ISSUE TITLE
Create new Docker image config for the DSS service

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#288]
## Why
Following the progress made in #287 and its resulting follow-up issue, we now have a replicable means of compiling and building the DSS service.

We now need to integrate it in the CAMI Cloud inside its own separate container.

## What
* [x] a new Docker configuration is created for the DSS service that takes into account:
    * [x] the container is created using an Ubuntu 16.04 image
    * [x] the container is configured to include DSS service's dependencies defined in #289
    * [x] the container is configured to automatically build the DSS service using the script that resulted from #287's investigation

**Comment by asorici** [comment]
This has been handled in PR #318. Closing, thank you!
