### ISSUE TITLE
Document dependencies required for running the DSS build script 

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#289]
## Why
Following the investigation done in #287 and the follow-up issue that resulted in a script that compiles & builds the DSS service, we need a precise list of Ubuntu 16.04 dependencies required for running it. 

## What
* [x] a list of packages and libraries required for the successful building of the DSS service is established on this issue as a comment, taking into account for each:
   * the exact command to install
   * the exact version of the library and package used - this is essential to ensure that we get the same results every time the DSS service is rebuilt

**Comment by sabljakovich** [comment]
The Visual Studio projects has all the dependencies included inside of the packages.config file. Also, the docker image used for this project includes everything necessary for installing packages (NuGet) and knows how to compile a .net project. 

> This image includes ONBUILD triggers that adds your app source code to /usr/src/app/source, restores NuGet packages and compiles the app, placing the output in /usr/src/app/build.
