### ISSUE TITLE
Add support for SNG Gateway tracing in health measurements & home monitoring data

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#290]
## Why
Health measurements and environment monitoring events need to be accompanied by traceability metadata for control and debugging purposes.

The CAMI data model needs to be augmented to include an identifier of the gateway that collects and forwards health or home monitoring data to the CAMI Cloud.

## What
* [x] the measurement model is adapted to include a reference to the originating SNG Gateway
    * the resulting field will be `NULL` for measurement that didn't originate from the Gateway
* [x] the API documentation is updated accordingly to reflect the changes

**Comment by asorici** [comment]
Completed in PR #306. Closing, thank you!
