### ISSUE TITLE
Push Linkwatch Health measurement to CAMI Insertion  endpoint

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#292]
## Why
Following the progress in #254, health measurements are no longer sent directly to the CAMI Store, but go through an _insertion_ and _analysis_ step prior to being inserted in the database.
The health measurements retrieved via the Linkwatch mobile platform have to be directed towards the new CAMI Insertion endpoint.

## What
  - [ ] the HTTP call to insert Linkwatch Health measurements into CAMI is updated to reflect the new API

**Comment by tobiasbrodencnet** [comment]
The LinkWatch exporter is now updated with the new endpoint, deployed and running. Test done to see that new measurements appears in RabbitMQ with consumer.py.

It's possible to manually export older measurement if necessary.
