### ISSUE TITLE
Embed Google Calendar widget inside the Linkwatch web interface for CAMI

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#297]
## Why
In #293 we outlined that the Linkwatch based web-interface is to become the default one for CAMI on PCs and tablets.
Consequently, the interface needs to display all the data that is currently managed by the CAMI System, including the schedule of activities (medication reminders, physical exercise sessions, programmed health measurements, leisure).
In order to prepare quickly for the December review and for participation to the AAL Forum, a quick solution is to embed the Google Calendar backend to each CAMI user account within the web interface.

## What
  - [ ] a Google Calendar display widget is included in the CAMI Linkwatch interface
  - [ ] the Widget displays in a tabbed view, the 3 types of calendars associated with a CAMI user account: medication, exercises, leisure

**Comment by asorici** [comment]
@tobiasbrodencnet please leave a status update on this issue.
Is it something we can expect for the upcoming field trials, or will we handle it later?
If it is the latter please close this one and we will reopen it at the appropriate time.

**Comment by tobiasbrodencnet** [comment]
This will be need to be put later after the first field trial.
