### ISSUE TITLE
Implement upward/downward weight trend analysis in DSS

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#298]
## Why
Following the progress in #288, we want to deploy the DSS in the CAMI Cloud and have it take over all the health measurement analysis and home monitoring event processing.
This means that it will also replace the current functionality implemented in the medical compliance module.
One of these simple analysis task is detection of an sudden increase or drop in the weight of an end-user.

## What
  - [x]  upon receipt of new weight measurement, DSS retrieves previous value from CAMI Store and performs comparison
  - [x] if the difference exceeds a given threshold (2 kg), a notification is outputted by the DSS
  - [x] depending on the sign of the difference (i.e. increase or decrease in weight), the notification will suggest having lighter meals or eating a more consistent one

**Comment by asorici** [comment]
The notification is actually a combination of two items:
  - inserting a corresponding entry in the User Journal
  - making a call to send a push notification to the CAMI iOS application

**Comment by sabljakovich** [comment]
#299 testing push notification integration
