### ISSUE TITLE
Implement lower/upper threshold analysis for heart rate in DSS

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#299]
## Why
Following the progress in #288, we want to deploy the DSS in the CAMI Cloud and have it take over all the health measurement analysis and home monitoring event processing.
This means that it will also replace the current functionality implemented in the medical compliance module.
One of these simple analysis task is the detection of an alarmingly low/high heart rate

## What
  

 - [x] when a new heart rate measurement arrives the DSS inspects the value, comparing it with a low threshold (50) and a high-one (120). 
  - [x] if the value exceeds any threshold a corresponding notification (see comment in #298) is sent to the end user and the caregiver

**Comment by sabljakovich** [comment]
Do I need to make sure heart rate is irregular for a period of time before sending a notification? If yes for how long?

**Comment by asorici** [comment]
This would depend on how frequently you receive heart rarte measurements from the sensor, which depends on the type of the sensor (e.g. for a smart watch using Google Fit, it's once every 5 min).

For now, instead of using a time-based window, consider looking at an item based one. That is, if the last 3 measurements are out of the ordinary, then send a notification.

**Comment by sabljakovich** [comment]
#299 testing push notification integration
