### ISSUE TITLE
Save analyzed health measurements into CAMI Store from DSS

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#300]
## Why
Following the outline of #298 and #299, the DSS performs the analyses that were originally a part of the medical compliance module.
The DSS must be capable of storing the analysed (and ok) measurements in the CAMI Store

## What
  - [x] implement the API calls that store a health measurement in the CAMI Store from the DSS

## Notes
See the [CAMI Store API documentation](cami.vitaminsoftware.com:8008/api/documentation/) for reference.

**Comment by sabljakovich** [comment]
#300 exchange and handlers integration
