### ISSUE TITLE
Save journal entry for new measurement into CAMI Store from DSS

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#301]
## Why
Following the outline of #298 and #299, the DSS performs the analyses that were originally a part of the medical compliance module.
The DSS must be capable of storing the result of the analysis (especially the abnormal ones) as Journal Entries in the CAMI Store.

## What
  - [ ] implement the API calls that store a journal entry referencing a health measurement in the CAMI Store from the DSS

## Notes

See the [CAMI Store API documentation](http://cami.vitaminsoftware.com:8008/api/documentation/) for reference.

**Comment by sabljakovich** [comment]
#300 exchange and handlers integration
