### ISSUE TITLE
Unit Test DSS Measurement Processing

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#322]
## Why
Before moving the DSS into production we need to test that it correctly handles the typical flow of measurement processing. Consequently, a unit testing checklist is defined to verify correct processing. We use sequences of API calls defined using CAMI Postman [Insertion](https://www.getpostman.com/collections/6b82b9347f6e2a1e7eec) and [Store](https://www.getpostman.com/collections/de4c6f7657d113ec135a) collections to perform insertion of measurements in the Event Stream Manager (RabbitMQ exchanges) and retrieval of data that needs to be observed in the CAMI Store.

### Pulse Measurement
  1) Insert a **normal** pulse measurement using the `pulse measurement insertion test` from the CAMI Insertion collection
  2) Verify that the measurement reaches the CAMI Store (use the Get All Measurements test from CAMI Store collection)
  3) Insert an abnormal pulse measurement that is either _lower_ than `min_threshold` or _higher_ than `max_threshold`
  4) Observe the following:
      - same check as in step 2
      - there is an entry, which is the most recent one, in JournalEntries for the user ID for which the measurement was taken
      - using the consumer.py script or the [RabbitMQ management admin](http://141.85.241.224:15673/#/) verify that a _push notification_ for **both** end-user and caregiver have been sent by checking the [push_notifications queue](http://141.85.241.224:15673/#/queues/cami/push_notifications).

### Weight measurements
  1) Steps 1 and 2 are the same as for pulse measurements.
  2) Insert a weight measurement that is 2 kg heigher or lower than the previous one.
  3) Observe the following:
     - existence of the measurements in the CAMI Store
     - there is an entry, which is the most recent one, in JournalEntries for the user ID for which the measurement was taken stating that the weight measurement is not ok
     -  using the consumer.py script or the [RabbitMQ management admin](http://141.85.241.224:15673/#/) verify that a _push notification_ for **both** end-user and caregiver have been sent by checking the [push_notifications queue](http://141.85.241.224:15673/#/queues/cami/push_notifications).

**Comment by sabljakovich** [comment]
I had a problem with "value" property in JSON response since the "value" is a keyword in C#. For now, I push "Value" with the capital V into measurements. I think this is not a big problem but will be fixed next week.  @asorici
