### ISSUE TITLE
CAMI iOS app sends ack/postpone event when user interacts with reminder

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#361]
## Why
As a developer of CAMI I wish for reminder management to be handled uniformly in the system.
Since reminders may be acknowledged from several places in the system (e.g. from the iPhone app, from the Linkwatch web interface, from the Pepper robot tablet), status update of a JournalEntry needs to be carried out from a single point in the CAMI System.

Currently, the iOS app applies a direct PATCH operation to the `acknowledged` field of a JournalEntry.
This behavior needs to change and leave it to the DSS to apply the corresponding update.

## What
  - [x] automatic patch of JournalEntry is no longer performed
  - [x] the CAMI iOS app sends a **Reminder Acknowledged** event of category USER_NOTIFICATION which carries the required information to reference **the corresponding activity** and the **original  Reminder Issued event** which has been issued when the reminder was sent to the iOS app.

  - [x] implement a mechanism to periodically update/retrieve the `acknowledged` status of JournalEntries from the CAMI Store

**Comment by rtud** [comment]
I've filed #385 & #396 to handle the first 2 checkboxes of this issue, thank you!

**Comment by rtud** [comment]
This issue has been resolved, part from #385 that is pending the resolved of #362. Closing, thank you!
