### ISSUE TITLE
Define Reminder ACK/Postpone/Ignored event model

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#363]
## Why
As a developer of CAMI I wish for reminder management to be handled uniformly in the system.
Since reminders may be acknowledged from several places in the system (e.g. from the iPhone app, from the Linkwatch web interface, from the Pepper robot tablet), status update of a JournalEntry needs to be carried out from a single point in the CAMI System.

Following the outline of #361 and #362, the iOS app and the DSS need to communicate using events from the USER_NOTIFICATION category.
The model of these events needs to be established. 

## What
  - [x] The format for events of type USER_NOTIFICATION which signal reminder issuing and acknowledging is defined, taking into account:
    - a means to uniquely identify the event 
    - a means to identify the journal entry whose state needs to be updated 
    - a means to identify the activity to which the event and journal entry refer to
  - [x] The format of the event and documented example instances are added as comments to this issue

**Comment by AlexRL** [comment]
The suggested format is the following:

```json
{
    "category": "user_notifications",
    "content": {
         "name": "reminder_acknowledged",
         "value_type": "complex",
         "value": {
             "ack": "ok",
             "user": { "id": user_id },
             "activity": { "id": reference_id }
         },
         "annotations": {
              "timestamp": timestamp,
              "source": "ios_app"
         }
     }
}
```

**Comment by asorici** [comment]
It is agreed to use the format proposed above during the field trials.
Closing with promise to revisit upon future need.
Thank you!
