### ISSUE TITLE
DSS analyzes motion sensor data

### ISSUE THREAD

**Issue by AlexRL** [cami-project/cami-project#378]
## Why
For the first stage field trials the defined scenarios require the analysis of presence events triggered by the motion sensor connected to the SNG Gateway.
The requirements of the scenario are detailed in the WHAT section.

## What
  - [x] detect when motion sensor is triggered
  - [x] determine user for which the event happens
  - [x] determine locales (lang + timezone) for end user
  - [x] localize timestamp of event
  - [x] if first trigger this morning => send reminder for blood pressure measurement (see also #362, #364)

**Comment by asorici** [comment]
The developments in this issue have been merged to master in PR #384 and are being tested in #390.
Closing and opening follow-ups if needed after testing. Thank you!
