### ISSUE TITLE
Enable filtering by user id in enduser profile endpoint

### ISSUE THREAD

**Issue by AlexRL** [cami-project/cami-project#379]
## Why
As a developer of CAMI, I want to be able to use the enduser profile endpoints to retrieve data about the elderly user and his/her caregivers. Since a profile belongs to a user, filtering by the corresponding user id is often encountered.

## What
  - [x] enable filtering by exact user id in enduser and caregiver profile endpoints

**Comment by asorici** [comment]
Handled in PR #384.
