### ISSUE TITLE
DSS implements step count analysis

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#388]
## Why
In the upcoming [first stage field trials](https://docs.google.com/document/d/1-FrxePmuTQws56OMuRp0Hkt1dujsNQKuyD2_GyLOlwg/edit) one of the scenarios regards an analysis on the number steps taken by the user during the day, which are recorded by the Fitbit bracelet.
The DSS needs to implement the logic that sends the notifications based on the evaluation of the step count.

## What
  - [ ] DSS implements analysis of daily step measurements for each user.

**Comment by asorici** [comment]
@sabljakovich please comment on the status of this issue. 
Close it as soon as it is merged into master and the tests in #389 are passing.
Thank you!

**Comment by rtud** [comment]
@sabljakovich: What's the status with this?

I know you've already made several tests for this in #389, so can we consider this finished?

Thank you!

**Comment by asorici** [comment]
Steps analysis tested successfully, merged in PR #415.
Closing, thank you!
