### ISSUE TITLE
Test DSS step count handler for first stage field trials

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#389]
## Why
Before launching this functionality live in the first stage field trials, we need to ensure that the scenario where notifications are sent based on the number of steps performed during a day runs correctly.

## What
The following checklist can be followed to ensure that all 3 types of possible notifications are handled
  - the Timer interval in the DSS is modified **for testing purpose** from one day to one minute (i.e. the analysis runs every minute)
  - before each test, all the `steps` measurements for the current day, stored in the **dev** machine, are deleted (use the [Django Admin](141.85.241.224:8008/admin/) interface for this).
  - then perform the following steps:
    - insert a steps measurment with a value of 500, with the start and end timestamps that are 1h apart (see the Notes part for an example form of a `steps` JSON). Make sure that the start_ts is 5h earlier than your current UTC timestamp (UTCnow)
    - wait for one minute and check that the corresponding JournalEntry for the **caregiver** is created in the [CAMI Store Admin Interface](http://141.85.241.224:8008/admin/store/journalentry/) with an alert for steps < 1000 is present

    - insert a new steps measurement with a value of 1000, with the start_ts being equal to the previous end_ts
    - wait for one minute and check that the corresponding JournalEntry for the **end-user** is created, with an alert for steps > 1000, but steps < 2000

    - insert a new steps measurement with a value of 6000, with the start_ts being equal to previous end_ts
    - wait for one minute and check that the corresponding JournalEntry for the **end-user** is created, with a notification to congratulate for steps > 6000

## Notes
```json
{
  "measurement_type": "steps",
  "unit_type" : "no_dim",
  
  "timestamp": 1507029180,
  
  "user": "/api/v1/user/2/",
  "device": "/api/v1/device/12/",
  "value_info": {
    "value": 121,
    "start_timestamp": 1507028160,
    "end_timestamp": 1507029180
  }
}
```

**Comment by rtud** [comment]
@sabljakovich: please add a time estimate to this issue using the corresponding ZenHub feature:

![estimate field in zenhub interface](http://mq.d.pr/h1k6TX.jpg)

Thanks!

**Comment by sabljakovich** [comment]
Tested

**Comment by asorici** [comment]
We need to still test this on the dev machine and deploy the new build of the DSS to production.

**Comment by asorici** [comment]
Tested and deployed!
