### ISSUE TITLE
Test MotionHandler and ReminderHandler behavior end-to-end for first stage field trials

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#390]
## Why
Before launching this functionality live in the first stage field trials, we need to ensure that the scenario where BP measurement reminders are sent following sensor movement first time in the morning runs correctly.

## What
The following checklist has to be followed:

1. Restart the DSS service on the CAMI dev machine
2. Adapt the example CAMI Insertion [Python consumer script](https://github.com/cami-project/cami-project/blob/master/insertion/example/consumer.py) to listen for USER_NOTIFICATION events from the dev machine.
3. Start the consumer script in a command line interface. 

4. Send a motion detection event (see Notes section for example format), with a timestamp that captures a time between 6AM and 11AM (localized time) for the current day. Use https://www.epochconverter.com/ to get an appropriate timestamp.

5. Inspect the [Admin interface](141.85.241.224:8008/admin/store/journalentry/) to see that the corresponding JournalEntries (reminders for BP measurement) have been created for both **end-user** and **caregiver**.

6. Inspect the output of the consumer.py script to check that the corresponding `reminder_sent` event has been issued.

7. From here onwards, there are 3 paths that need to be checked:
  - leave the reminder unanswered for 10 minutes (alternatively, modify the code in DSS, just for this test, to have a 1 min timeout)
      - check that a corresponding JournalEntry (alert to **caregiver**) has been sent
  - using Postman, send an event of category `reminder_acknowledged` with a "snooze" value for the `ack` field in the value JSON. Make sure to include the same journal entry id, as the one that was created at step 5 for the **end-user**
      - in the Admin Interface, check that the `acknowledged` field of the JournalEntries sent at step 5 for **end-user** and **caregiver** have been set to false
      - check that a _new_ JournalEntry (the alert one) has been sent to the **caregiver** to ask him to call the end-user and remind him to take the measurement.
  - using Postman, send an event of category `reminder_acknowledged` with an "ok" value for the `ack` field in the value JSON. Make sure to include the same journal entry id, as the one that was created at step 5 for the **end-user**
      - in the Admin Interface, check that the `acknowledged` field of the JournalEntries sent at step 5 for **end-user** and **caregiver** have been set to false 
      - wait for 10 minutes (or the amount set for testing) without sending any BP measurement
      - check that the corresponding alert JournalEntry for the **caregiver** appears in the Admin Interface
      - in an alternative check, send a BP measurement and observe that no new alert is sent to the caregiver (using the Admin Interface)
 

## Notes
Motion Sensor Event
```json
{
	"category":"USER_ENVIRONMENT",
	"content":{
		"name":"presence",
		"value_type":"complex",
		"value":{
			"alarm_motion":true,
			"alarm_tamper":true,
			"battery_level":85,
			"sensor_luminance":174,
			"sensor_temperature":28.8
		}
	},
	"annotations":{
		"timestamp":1508398571,
		"source":{
			"gateway":"/api/v1/gateway/1/",
			"sensor":"/api/v1/device/9/"
		}
	}
}
```

BP Measurement
```json
{
	"measurement_type": "blood_pressure",
	"unit_type" : "mmHg",
	
	"timestamp": 1506786209,
	
	"user": "/api/v1/user/2/",
	"device": "/api/v1/device/4/",
	"value_info": {
		"pulserate": 56,
		"diastolic": 63,
		"systolic": 114
	}
}
```

**Comment by rtud** [comment]
@sabljakovich: please add a time estimate to this issue using the corresponding ZenHub feature:

![estimate field in zenhub interface](http://mq.d.pr/h1k6TX.jpg)

Thanks!

**Comment by sabljakovich** [comment]
All paths are tested.
