### ISSUE TITLE
Create special icon for Steps notifications

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#393]
## Why
During the first stage field trials, one of the tested scenarios is that of receiving notifications based on the number of steps (nr<1000, 1000< nr<2000, nr > 6000). They range from medium severity to an actual congratulations message.
We want to have a dedicated visual form for the steps notifications in the iOS app.

## What
  - [ ] create an icon that signals the fact that we are dealing with a steps notification (as we have for pulse, BP and weight)
  - [ ] create a color theme that indicates whether the message is a warning (e.g. steps < 2000) or a congratulation (steps > 6000)

**Comment by rtud** [comment]
This will be handled in #383, thank you!

**Comment by rtud** [comment]
@asorici: After reviewing the existent iOS app code, I found we've already added support for steps notifications.

To get the corresponding icon for steps, the respective Journal Entry needs to be of `"type": "steps"`.

Thank you!
