### ISSUE TITLE
Create Google Accounts for Field Trial End Users

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#397]
## Why
For the upcoming field trials we need to create google calendar accounts for each of the precreated end-user accounts on the CAMI Cloud. This is needed in order to set medication, exercise or appointment activities for each end-user.

## What
  - create the google test accounts with the following credentials:
```
Romania, End User 1
Email: cami.trial.ro.1@gmail.com
Google Pass: camifieldtrials-123$
URL: /api/v1/user/7/
Poland, End User 1
Email: cami.trial.pl.1@gmail.com
Google Pass: camifieldtrials-123$
URL: /api/v1/user/6/
Denmark, End User 1
Email: cami.trial.dk.1@gmail.com
Google Pass: camifieldtrials-123$
URL: /api/v1/user/5/
```

**Comment by asorici** [comment]
Accounts have been created and the calendars used in the CAMI System have been configured.

**Comment by aliviateeh** [comment]
What are the associated device id range ???

    "devices": {
        "ble_5C:31:3E:00:66:A0_": {
            "cc_device": "/api/v1/device/4/", 

Denmark, End User 1
Email: cami.trial.dk.1@gmail.com
Google Pass: camifieldtrials-123$
URL: /api/v1/user/5/

**Comment by asorici** [comment]
Closing this issue following clarifications in today's meeting and confirmation that the setup for the Danish gateway is sending data.
Thank you!
