### ISSUE TITLE
Google Calendar fetch not working for field trials account

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#408]
## Why
Following the changes brought by #406 in order to have multiple user support for the Google Calendar activity sync, fetching the new users' calendars fails:

```
ERROR 2017-11-02 07:49:09,856 google_calendar_backend 11 139836005697280 [google_calendar_backend] Cannot retrieve remote calendar: ai8jdd4j5tnrkpg4pdh5evqi7s@group.calendar.google.com
Traceback (most recent call last):
  File "/cami-project/google_calendar/google_calendar_backend.py", line 101, in get_calendar
    res = req.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/users/me/calendarList/ai8jdd4j5tnrkpg4pdh5evqi7s%40group.calendar.google.com?alt=json returned "Not Found">
```

## What
* [ ] google calendar fetch for multi users is investigated and follow-up issues are created as required to successfully retrieve events for all users

## Notes
After a preliminary investigation, we believe the reason behind calendar fetch fails might be the fact that we're trying to access the new users' calendars using the credentials for the CAMI Demo account.

**Comment by asorici** [comment]
Fixed all errors pertaining to user credentials and OAuth2 authorization.
Calendar retrieval is working for the 3 field trial accounts. (See PR #410)
Closing, thank you!
