### ISSUE TITLE
Add UDIDs for iPhone/iPad devices from danish and polish end users

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#411]
## Why
For the first stage field trials the CAMI App needs to be installed on user's devices.

## What
  - add the following 2 UDIDs and issue a new release of the app:
    - `04492523902E80015028052923933576AE0A117395179008`
    - `044F399B3E298001424403209793183938592F0F4EDD1B08`
    - `226482e4a4e8e3ab79ce4f90ef1f2d27cf784855`

**Comment by rtud** [comment]
I've added the **3** new devices to the deployment certificates and exported a new build that can be [downloaded via CAMI's official Google Drive](https://drive.google.com/open?id=1jgRjyjAb-IJurWe_MlZMvMRtishAcYuA).

I've also made a minor hack to the Elder's screen that will prevent buttons overlapping the text on iPads.

**Comment by rtud** [comment]
Here's another build that also removes references to Jim from the iOS app's UI and default app data: https://drive.google.com/open?id=1dmVgGXSk-PXYfIQ4EhXHvsRm5PYPussm

**Comment by asorici** [comment]
@rtud Please add the following UDIDs to the whitelist.

`e5b144c242fd6eecb51012ebcd6602df569ee3d3`
`9a4ab8e864ef4d6ba2ade64aa9ab52227ede87cc`

Our polish partners will use two new tablets (one for caregiver, one for end-user) during the field trials.
Thank you!

**Comment by rtud** [comment]
@asorici: The last 2 UDIDs aren't valid so for the time being I've only used the 1st 2. Here's an updated [build link via the official CAMI GDrive](https://drive.google.com/open?id=1aGjxzdbm164OAWrBMv-dxkEU8N7sGioa). Thank you!

**Comment by rtud** [comment]
@asorici: Here's [the latest iOS build](https://drive.google.com/open?id=1qJ_MfzU5jM4DnCnqHDUrn2X73IWqbZBe) that includes:
- an additional 2 UDIDs added to the supported devices list
- fix for Activities stream fetch failing for Caregivers

Closing this, thank you!
