### ISSUE TITLE
Latest activities endpoint isn't filtering results by user

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#416]
## Why
For the upcoming CAMI Field Trials, we need to adapt the iOS app and system to work for multiple users.

## What
* [ ] fetching data via the [Activities endpoint](http://cami.vitaminsoftware.com:8008/api/v1/activity/last_activities/?user=2) filters the results by user when using the optional url  parameter `user`

## Notes
Currently the endpoint delivers activities from all the known users.

**Comment by asorici** [comment]
Handled in PR #418.
Closing, thank you!
