### ISSUE TITLE
Add UDID for danish field trial user

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#427]
## Why
The personal device of a danish elderly user will be used during the field trials in Denmark. It therefore needs to be whitelisted in the CAMI app.

## What
  - whitelist the following UDID: `ccf6eef4409ac31b25d7706a90c06a1a37bcdb8c`

**Comment by rtud** [comment]
@asorici: I've exported [a new build](https://drive.google.com/open?id=1aHgsnP6mZxrxuxbs__0J1X2-gVU62jRr) whitelisting the above mentioned UDID. Closing, thank you!
