### ISSUE TITLE
Generate caregiver notification for start/end event of physical exercise

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#428]
## Why
For the upcoming review we need to demonstrate a minimum level of integration of the physical exercise module with the CAMI Cloud. 
An implementation exists which sends a start and an end event when a physical exercise begins or ends.
To have a confirmation of these events, a notification must be sent to the caregiver informing of the start and end of a physical exercise. 
A notification of the result of the exercise must be sent to the end-user as well, to be visible in the Diary widget of the CAMI Linkwatch web interface.

## What
  - [x] upon reception of an `exercise_started` event a notification (JournalEntry + PushNotification) of type `exercise` is sent to the caregiver
  - [x] upon reception of an `exercise_ended` with the same `session_uuid` as the one from a _previous_ `exercise_started` one, a notification is sent **to both** end-user and caregiver
  - [x] the notification to the end-user should be accompanied by an analysis of the compliance level:
     - if it is below 30%: Add suggestion to be more focused next time
     - if between 30 and 60% percent: Add suggestion for keep improving
     - if over 60%: Add congratulation

## Notes
Form of the event sent when an exercise starts
```
{
    "category": "user_notifications",
    "content": {
         "name": "exercise_started",
         "value_type": "complex",
         "value": {
             "user": { "id": 2 },
             "exercise_type": "arm_gymnastics",
             "session_uuid" : <uuid4 value of exercise session>
         }
    },
    "annotations": {
          "timestamp": <UTC-timestamp>,
          "source": "exercises"
    }
}
```

Form of the event sent when an exercise ends:
```
{
    "category": "user_notifications",
    "content": {
         "name": "exercise_ended",
         "value_type": "complex",
         "value": {
             "user": { "id": 2 },
             "exercise_type": "arm_gymnastics",
             "session_uuid" : <uuid4 value of exercise session>,
             "score": <float-value percentage correct>
         }
    },
    "annotations": {
          "timestamp": <UTC-timestamp>,
          "source": "exercises"
    }
}
```

- Notice that the exercise sessions **must match** based on the `session_uuid` field.
- Use the `exercise_type` field to indicate in the JournalEntry Message what type of exercise has started/ended
- Use the `score` field (interpreted as a percentage) to indicate how correct the execution of the exercise was.

- The `message` and `description` of the JournalEntries that are part of the notification are the following:

  - start notification to caregiver:
    * message: Physical Exercise Started.
    * description: The person under your care has started a physical exercise of type `exercise_type`.
 
  - end notification to caregiver:
    * message: Physical Exercise Ended
    * description: The person under your care has finished the `exercise_type` exercise with a compliance of `score`%.

  - end notification to end-user:
    * message: You finished your workout!
    * description: Hey! You finished your `exercise_type` with `score`% compliance.
       - if score <= 30: How about focusing more next time?
       - if score > 30 && score <= 60: Keep improving!
       - if score > 60: You performed well!

**Comment by sabljakovich** [comment]
Implemented and tested on the dev machine. @asorici  I left some comments in the code where I was unsure.
