### ISSUE TITLE
Implement demo for measurement retrieval from Withings wifi scale

### ISSUE THREAD

**Issue by asorici** [cami-project/cami-project#47]
## Why

We want to have this as the first instance of real data collection from a device that can be integrated into CAMI.
## What

The code comprises an API similar to the medical_compliance one. It involves:
- creating subscribe/unsubscribe endpoints that register for notifications of new measurements from the registered Withings device (WiFi weight scale)
- setting up a callback URL called each time (through a POST request) a notification for new measurements arrives
- creating async tasks (using Celery) that retrieve the new measurements after a notification is made and store them in the CAMI store
## Notes
- need to create a model that defines a CAMI user profile, such as to link it to stored medical compliance, frontend notifications, as well as retrieved measurement records

**Comment by rtud** [comment]
@asorici: This has been implemented into the CAMI Cloud system, and also inside the iOS front end app. This will also be documented inside issue #82. Closing, thank you!
