### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by paraschivionut** [cami-project/cami-project#75]
## Why
Health check endpoints are used across industry to monitor the health of APIs. These are usually included in automated monitoring systems, such as OpsGenie. When a health check for an API fails, a sysadmin or developer is pinged to investigate the problem.

## What
* [x] health check fails if the connection to the database fails
* [x] health check fails if the connection to the message queue fails

## Notes
How to check connection to the DB: read the state of the database (run a dummy query OR see if there's an api that can do this). The database is the `cami-store` docker instance that contains a MySQL instance.

How to check connection to the message queue: it's deployed on the `cami-rabbitmq` docker container that contains a [rabbitmq server](https://www.rabbitmq.com). We use [celery](http://celery.readthedocs.io/en/latest/) to communicate with the queue.

Suggestion: include the health check endpoint in the CAMI frontend project.

**Comment by paraschivionut** [comment]
@cretualexandru in the fille `medical_compliance/medical_compliance/api/tasks.py`you will find a task named `fetch_weight_measurement`.
An example of how this can be invoked can be found in `withings_tasks.py`
`
from tasks import fetch_weight_measurement
…..
fetch_weight_measurement.delay(…) # delay is a celery specific param
`

As you need to integrate this in the `frontend` project, you can add a dummy task (or whatever you need to call to test the queue's state) in `frontend/api/tasks.py`

**Comment by cretualexandru** [comment]
Closed because health check endpoint was implemented.
