### ISSUE TITLE
Documentation for how to trigger a build

### ISSUE THREAD

**Issue by paraschivionut** [cami-project/cami-project#81]
## Why

All the development flow, starting from how you save the changes, create a new build on Docker Hub and install it on Rancher should be well documented. Everyone should be able to follow these instructions.
## What

Create documentation and refactor the existing one with the exact steps required.

**Comment by rtud** [comment]
This was tended to by @cretualexandru in #160, and the procedure is documented in [DEPLOYING.md](https://github.com/cami-project/cami-project/blob/master/DEPLOYING.md)
