### ISSUE TITLE
Write dev flow document

### ISSUE THREAD

**Issue by paraschivionut** [cami-project/cami-project#82]
## Why

Right now, the project has a lot of docker containers and it is unclear when you run the client locally to which backend do you actually connect.
All these steps should be clear such that anyone with no apriori knowledge of the project should be capable of bootstraping the dev environment and running the mobile client linked to it or to the production server which is now deployed on Digital Ocean using Rancher.
## What
- [ ] Create document explaining how you can set up the back-end dev environment
- [ ] Create document explaining how you can set up the client dev environment and how you can link it with the local backend & production deployed on Digital Ocean

**Comment by aismail** [comment]
Also with this occasion, clean up the existing documentation end-to-end and make sure it's neat. Thank you!
