### ISSUE TITLE
Create Celery task that grabs Heart Rate data from the Google Fit API

### ISSUE THREAD

**Issue by rtud** [cami-project/cami-project#99]
## Why
As a Caregiver using the CAMI system to take care of an Elder, having updated information on his heart rate and step count, helps me understand if his current condition is in order, or if there are any problems regarding his overall health or lack of exercise. This in turn will help CAMI and myself to take action in time.

After defining how we'll store the Heart Rate information in #97 and creating a means of accessing it in #98, we then have to start implementing the functionality of getting the actual data from Google Fit.

## What
* [x] a task that handles fetching of the Google Fit data is implemented

**Comment by cretualexandru** [comment]
After all, there was no need to separate grabbing data and saving the data in two different tasks. Only one task that handles both actions was created, in PR #101. Closed!
